export const robots = [
    {
        id:  434,
        first_name: 'santosh ',
        last_name: 'sardar',
        name: 'santosh  sardar',
        submit_date: '2022-01-21 16:21:44+05:30',
        phone: '8080789578',
        client_name: 'Xiaomi Redmi Note 7S',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'dilasa sanstha and aniket ngo',
        state_id: 26,
        district_id: 509,
        district_name: 'Yavatmal'
    },
    {
        id:  688,
        first_name: 'saurabh',
        last_name: 'khandagale',
        name: 'saurabh khandagale',
        submit_date: '2022-01-21 02:38:22+05:30',
        phone: '8669047568',
        client_name: 'realme RMX2151',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'ART Sanstha Yavatmal',
        state_id: 26,
        district_id: 509,
        district_name: 'Yavatmal'
    },
    {
        id:  687,
        first_name: 'Sahadev',
        last_name: 'K',
        name: 'Sahadev K',
        submit_date: '2022-01-20 18:50:15+05:30',
        phone: '2486139750',
        client_name: 'Xiaomi Redmi Note 4',
        client_version: '7.0 M',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 22,
        district_id: 438,
        district_name: 'Indore'
    },
    {
        id:  6,
        first_name: 'b',
        last_name: 't',
        name: 'b t',
        submit_date: '2022-01-20 18:23:12+05:30',
        phone: '7283833833',
        client_name: 'samsung SM-M127G',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Adoni Area Rural Development Initiatives Programme (AARDIP)',
        state_id: 17,
        district_id: 324,
        district_name: 'Darrang'
    },
    {
        id:  399,
        first_name: 'Amol',
        last_name: 'Sakarkar',
        name: 'Amol Sakarkar',
        submit_date: '2022-01-20 01:09:53+05:30',
        phone: '9421852014',
        client_name: 'vivo vivo 1723',
        client_version: '9 O_MR1',
        app_version: '2.0',
        org_name: '',
        state_id: 26,
        district_id: 509,
        district_name: 'Yavatmal'
    },
    {
        id:  686,
        first_name: 'Ganesh ',
        last_name: 'bhute',
        name: 'Ganesh  bhute',
        submit_date: '2022-01-19 20:26:30+05:30',
        phone: '9605100208',
        client_name: 'realme RMX3061',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'Akshay seva chandrapur',
        state_id: 26,
        district_id: 508,
        district_name: 'Chandrapur'
    },
    {
        id:  685,
        first_name: 'Aman',
        last_name: 'Indore ',
        name: 'Aman Indore ',
        submit_date: '2022-01-19 17:37:53+05:30',
        phone: '9425555576',
        client_name: 'HUAWEI BND-AL10',
        client_version: '9 O_MR1',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 22,
        district_id: 438,
        district_name: 'Indore'
    },
    {
        id:  684,
        first_name: 'Sandesh',
        last_name: 'dubey',
        name: 'Sandesh dubey',
        submit_date: '2022-01-19 17:36:29+05:30',
        phone: '9650655684',
        client_name: 'realme RMX3031',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 23,
        district_id: 481,
        district_name: 'Anand'
    },
    {
        id:  412,
        first_name: 'sanjiv',
        last_name: 'masram',
        name: 'sanjiv masram',
        submit_date: '2022-01-19 12:50:40+05:30',
        phone: '9309382188',
        client_name: 'realme RMX3063',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 508,
        district_name: 'Chandrapur'
    },
    {
        id:  683,
        first_name: 'VIJAY',
        last_name: 'PACHARE',
        name: 'VIJAY PACHARE',
        submit_date: '2022-01-19 01:21:32+05:30',
        phone: '9960435081',
        client_name: 'OPPO CPH2001',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 503,
        district_name: 'Wardha'
    },
    {
        id:  75,
        first_name: 'Gouri Krishna',
        last_name: 'Behera',
        name: 'Gouri Krishna Behera',
        submit_date: '2022-01-18 21:38:55+05:30',
        phone: '9861003892',
        client_name: 'OPPO CPH2325',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Shakti Organisation',
        state_id: 20,
        district_id: 395,
        district_name: 'Rayagada'
    },
    {
        id:  682,
        first_name: 'Ganesh',
        last_name: ' Gawande',
        name: 'Ganesh  Gawande',
        submit_date: '2022-01-18 19:46:26+05:30',
        phone: '9850116320',
        client_name: 'Xiaomi M2010J19SI',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'navvidyabahuudeshiy sanstha',
        state_id: 26,
        district_id: 509,
        district_name: 'Yavatmal'
    },
    {
        id:  681,
        first_name: 'arvind borkar',
        last_name: 'borkar',
        name: 'arvind borkar borkar',
        submit_date: '2022-01-18 17:41:22+05:30',
        phone: '9763079957',
        client_name: 'asus ASUS_X00TD',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 509,
        district_name: 'Yavatmal'
    },
    {
        id:  355,
        first_name: 'sandesh',
        last_name: 'dubey',
        name: 'sandesh dubey',
        submit_date: '2022-01-18 16:56:24+05:30',
        phone: '9650625684',
        client_name: 'realme RMX3031',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 508,
        district_name: 'Chandrapur'
    },
    {
        id:  680,
        first_name: 'Domu ',
        last_name: 'Singh',
        name: 'Domu  Singh',
        submit_date: '2022-01-06 01:11:56+05:30',
        phone: '8357928953',
        client_name: 'HUAWEI BKK-AL10',
        client_version: '8.1.0 O',
        app_version: '2.0',
        org_name: 'Darshan Foundation',
        state_id: 21,
        district_id: 409,
        district_name: 'Raipur'
    },
    {
        id:  61,
        first_name: 'Sushil',
        last_name: 'Oraon',
        name: 'Sushil Oraon',
        submit_date: '2021-12-31 16:36:54+05:30',
        phone: '9462192942',
        client_name: 'OnePlus DN2101',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 23,
        district_id: 481,
        district_name: 'Anand'
    },
    {
        id:  679,
        first_name: 'itots',
        last_name: 'kol',
        name: 'itots kol',
        submit_date: '2021-12-31 00:56:20+05:30',
        phone: '8240998378',
        client_name: 'samsung SM-F127G',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Ananya',
        state_id: 18,
        district_id: 327,
        district_name: 'Jalpaiguri'
    },
    {
        id:  678,
        first_name: 'ABCD',
        last_name: 'EFGH',
        name: 'ABCD EFGH',
        submit_date: '2021-12-30 23:22:30+05:30',
        phone: '8240998379',
        client_name: 'unknown unknown',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 18,
        district_id: 341,
        district_name: 'Kolkata'
    },
    {
        id:  677,
        first_name: 'itots',
        last_name: 'itots',
        name: 'itots itots',
        submit_date: '2021-12-30 18:01:32+05:30',
        phone: '8295201206',
        client_name: 'Genymobile Google Pixel 3',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'itots',
        state_id: 5,
        district_id: 73,
        district_name: 'Karnal'
    },
    {
        id:  12,
        first_name: '123456789@abcd.com',
        last_name: 'Tandel@&&&',
        name: '123456789@abcd.com Tandel@&&&',
        submit_date: '2021-12-28 22:59:29+05:30',
        phone: '9898989897',
        client_name: 'postman',
        client_version: '7.1.6',
        app_version: '1',
        org_name: 'FES-abcd',
        state_id: null,
        district_id: null,
        district_name: null
    },
    {
        id:  353,
        first_name: 'Bikram',
        last_name: 'Bhoi',
        name: 'Bikram Bhoi',
        submit_date: '2021-12-18 21:14:28+05:30',
        phone: '7735407287',
        client_name: 'realme RMX2185',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'RCDC',
        state_id: 20,
        district_id: 392,
        district_name: 'Balangir'
    },
    {
        id:  313,
        first_name: 'Raneet',
        last_name: 'Dehury',
        name: 'Raneet Dehury',
        submit_date: '2021-12-16 21:14:05+05:30',
        phone: '7657062878',
        client_name: 'vivo vivo 1906',
        client_version: '9 O_MR1',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 20,
        district_id: 374,
        district_name: 'Kendujhar'
    },
    {
        id:  531,
        first_name: 'Pritish',
        last_name: 'Behera',
        name: 'Pritish Behera',
        submit_date: '2021-12-16 18:19:29+05:30',
        phone: '7770906257',
        client_name: 'motorola motorola one vision',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 21,
        district_id: 409,
        district_name: 'Raipur'
    },
    {
        id:  530,
        first_name: 'Digambar',
        last_name: ' Umak',
        name: 'Digambar  Umak',
        submit_date: '2021-12-15 22:12:17+05:30',
        phone: '9822219589',
        client_name: 'vivo vivo 1820',
        client_version: '8.1.0 O',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 503,
        district_name: 'Wardha'
    },
    {
        id:  529,
        first_name: 'Sushanta ',
        last_name: 'Majhi',
        name: 'Sushanta  Majhi',
        submit_date: '2021-12-12 00:51:32+05:30',
        phone: '8260502992',
        client_name: 'vivo vivo 1820',
        client_version: '8.1.0 O',
        app_version: '2.0',
        org_name: 'Jana Kalman sanstha',
        state_id: 20,
        district_id: 394,
        district_name: 'Kalahandi'
    },
    {
        id:  528,
        first_name: 'jyotirmayee',
        last_name: 'Patel',
        name: 'jyotirmayee Patel',
        submit_date: '2021-12-11 17:05:38+05:30',
        phone: '8328985800',
        client_name: 'OPPO CPH1945',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 20,
        district_id: 373,
        district_name: 'Sundargarh'
    },
    {
        id:  527,
        first_name: 'Amol ',
        last_name: 'Kukade',
        name: 'Amol  Kukade',
        submit_date: '2021-12-07 22:16:38+05:30',
        phone: '7875874451',
        client_name: 'samsung SM-J720F',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 503,
        district_name: 'Wardha'
    },
    {
        id:  387,
        first_name: 'Bhaktaram',
        last_name: 'Majhi',
        name: 'Bhaktaram Majhi',
        submit_date: '2021-12-07 15:16:37+05:30',
        phone: '6371589066',
        client_name: 'samsung SM-T295',
        client_version: '9 O_MR1',
        app_version: '2.0',
        org_name: 'FRA Cell Boipariguda',
        state_id: 20,
        district_id: 397,
        district_name: 'Koraput'
    },
    {
        id:  388,
        first_name: 'Padmanaba',
        last_name: 'Khillo',
        name: 'Padmanaba Khillo',
        submit_date: '2021-12-07 02:32:34+05:30',
        phone: '9556898539',
        client_name: 'samsung SM-T295',
        client_version: '9 O_MR1',
        app_version: '2.0',
        org_name: 'FRA Cell Boipariguda',
        state_id: 20,
        district_id: 397,
        district_name: 'Koraput'
    },
    {
        id:  381,
        first_name: 'Dolagobinda',
        last_name: 'Khillo',
        name: 'Dolagobinda Khillo',
        submit_date: '2021-12-07 01:44:34+05:30',
        phone: '8018829129',
        client_name: 'samsung SM-T295',
        client_version: '9 O_MR1',
        app_version: '2.0',
        org_name: 'FRA Cell Boipariguda',
        state_id: 20,
        district_id: 397,
        district_name: 'Koraput'
    },
    {
        id:  526,
        first_name: 'Jagannath',
        last_name: 'Nayak',
        name: 'Jagannath Nayak',
        submit_date: '2021-12-07 01:04:12+05:30',
        phone: '8658945409',
        client_name: 'samsung SM-T295',
        client_version: '9 O_MR1',
        app_version: '2.0',
        org_name: 'FRA Cell Boipariguda ',
        state_id: 20,
        district_id: 397,
        district_name: 'Koraput'
    },
    {
        id:  448,
        first_name: 'Haradhan',
        last_name: 'Bhaina',
        name: 'Haradhan Bhaina',
        submit_date: '2021-12-06 01:34:23+05:30',
        phone: '6371152700',
        client_name: 'vivo V2129',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Manav Adhikar Seva Samiti (MASS)',
        state_id: 20,
        district_id: 369,
        district_name: 'Bargarh'
    },
    {
        id:  436,
        first_name: 'Pankajini',
        last_name: 'Dalabehera',
        name: 'Pankajini Dalabehera',
        submit_date: '2021-12-05 19:10:44+05:30',
        phone: '9777167616',
        client_name: 'OPPO CPH2325',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'regional centre for development cooperation',
        state_id: 20,
        district_id: 375,
        district_name: 'Mayurbhanj'
    },
    {
        id:  512,
        first_name: 'dilhar',
        last_name: 'bansod',
        name: 'dilhar bansod',
        submit_date: '2021-12-04 20:29:27+05:30',
        phone: '9527408204',
        client_name: 'OPPO F1f',
        client_version: '5.1.1 LOLLIPOP',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 505,
        district_name: 'Bhandara'
    },
    {
        id:  525,
        first_name: 'buti  pujari',
        last_name: 'pujari',
        name: 'buti  pujari pujari',
        submit_date: '2021-12-04 02:10:40+05:30',
        phone: '8260266291',
        client_name: 'Xiaomi Redmi 8A',
        client_version: '9 O_MR1',
        app_version: '2.0',
        org_name: 'Porevarthan, Malkangiri',
        state_id: 20,
        district_id: 398,
        district_name: 'Malkangiri'
    },
    {
        id:  29,
        first_name: 'Suryasing',
        last_name: 'Soren',
        name: 'Suryasing Soren',
        submit_date: '2021-12-01 17:56:09+05:30',
        phone: '8480542861',
        client_name: 'samsung SM-M315F',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 20,
        district_id: 374,
        district_name: 'Kendujhar'
    },
    {
        id:  524,
        first_name: 'Ganesh',
        last_name: 'Raut',
        name: 'Ganesh Raut',
        submit_date: '2021-11-27 14:57:16+05:30',
        phone: '9309540930',
        client_name: 'samsung SM-A105F',
        client_version: '9 O_MR1',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 503,
        district_name: 'Wardha'
    },
    {
        id:  523,
        first_name: 'Roshan',
        last_name: 'Rangari',
        name: 'Roshan Rangari',
        submit_date: '2021-11-26 20:33:36+05:30',
        phone: '9067819107',
        client_name: 'vivo V2101',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 505,
        district_name: 'Bhandara'
    },
    {
        id:  522,
        first_name: 'Shubham',
        last_name: 'Wanave',
        name: 'Shubham Wanave',
        submit_date: '2021-11-26 05:54:30+05:30',
        phone: '8657028650',
        client_name: 'Xiaomi Redmi 3S',
        client_version: '6.0.1 LOLLIPOP_MR1',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 502,
        district_name: 'Amravati'
    },
    {
        id:  521,
        first_name: 'mohini',
        last_name: 'kamble',
        name: 'mohini kamble',
        submit_date: '2021-11-26 04:45:35+05:30',
        phone: '7558444141',
        client_name: 'OPPO CPH2127',
        client_version: '11 Q',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 503,
        district_name: 'Wardha'
    },
    {
        id:  520,
        first_name: 'Tara',
        last_name: 'Kumbhalkar',
        name: 'Tara Kumbhalkar',
        submit_date: '2021-11-26 02:39:50+05:30',
        phone: '9764094864',
        client_name: 'OPPO RMX1805',
        client_version: '9 O_MR1',
        app_version: '2.0',
        org_name: 'FES',
        state_id: 26,
        district_id: 505,
        district_name: 'Bhandara'
    },
    {
        id:  519,
        first_name: 'JAGESHWAR',
        last_name: 'PAL',
        name: 'JAGESHWAR PAL',
        submit_date: '2021-11-26 01:51:59+05:30',
        phone: '8888653160',
        client_name: 'Xiaomi Redmi 6',
        client_version: '8.1.0 O',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 505,
        district_name: 'Bhandara'
    },
    {
        id:  516,
        first_name: 'BHAGWAN',
        last_name: 'UKEY',
        name: 'BHAGWAN UKEY',
        submit_date: '2021-11-26 01:32:42+05:30',
        phone: '8412823024',
        client_name: 'OPPO CPH1881',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 505,
        district_name: 'Bhandara'
    },
    {
        id:  514,
        first_name: 'Devendra',
        last_name: 'Thakare',
        name: 'Devendra Thakare',
        submit_date: '2021-11-26 00:33:53+05:30',
        phone: '9158344758',
        client_name: 'Xiaomi Redmi Note 7 Pro',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 503,
        district_name: 'Wardha'
    },
    {
        id:  518,
        first_name: 'prashant ',
        last_name: 'avchar',
        name: 'prashant  avchar',
        submit_date: '2021-11-25 23:56:26+05:30',
        phone: '9527265946',
        client_name: 'Xiaomi Redmi Note 5',
        client_version: '8.1.0 O',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 499,
        district_name: 'Buldana'
    },
    {
        id:  517,
        first_name: 'dilhar',
        last_name: 'bansod ',
        name: 'dilhar bansod ',
        submit_date: '2021-11-25 23:11:22+05:30',
        phone: '9923150895',
        client_name: 'OPPO F1f',
        client_version: '5.1.1 LOLLIPOP',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 505,
        district_name: 'Bhandara'
    },
    {
        id:  515,
        first_name: 'RAJKAMAL',
        last_name: 'UKEY',
        name: 'RAJKAMAL UKEY',
        submit_date: '2021-11-25 22:21:18+05:30',
        phone: '8390062358',
        client_name: 'vivo V2029',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 505,
        district_name: 'Bhandara'
    },
    {
        id:  513,
        first_name: 'BHAGWAT',
        last_name: 'patole',
        name: 'BHAGWAT patole',
        submit_date: '2021-11-25 21:16:50+05:30',
        phone: '9689885715',
        client_name: 'vivo vivo 1807',
        client_version: '8.1.0 O',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 499,
        district_name: 'Buldana'
    },
    {
        id:  511,
        first_name: 'Roshan',
        last_name: 'Savatwan',
        name: 'Roshan Savatwan',
        submit_date: '2021-11-25 19:17:58+05:30',
        phone: '8308588348',
        client_name: 'Xiaomi POCO M2 Pro',
        client_version: '10 P',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 505,
        district_name: 'Bhandara'
    },
    {
        id:  510,
        first_name: 'prakash Narayan ',
        last_name: 'Ingle',
        name: 'prakash Narayan  Ingle',
        submit_date: '2021-11-25 17:51:25+05:30',
        phone: '9922123194',
        client_name: 'asus ASUS_X008DA',
        client_version: '7.0 M',
        app_version: '2.0',
        org_name: 'Foundation for Ecological Security (FES)',
        state_id: 26,
        district_id: 506,
        district_name: 'Gondiya'
    }
];